# Generated by Django 4.2.15 on 2024-08-24 16:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(choices=[(0, 'Introduction to Information Technology'), (1, 'Networking Fundamentals'), (2, 'Software Development'), (3, 'Cybersecurity'), (4, 'Database Management'), (5, 'Cloud Computing'), (6, 'Web Development'), (7, 'Data Science and Analytics'), (8, 'Project Management in IT'), (9, 'Ethical Hacking and Penetration Testing')])),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'course')},
            },
        ),
    ]
